/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated/workouts'
import { Route as AuthenticatedTrainersRouteImport } from './routes/_authenticated/trainers'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMembershipsRouteImport } from './routes/_authenticated/memberships'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedDietRouteImport } from './routes/_authenticated/diet'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainersRoute = AuthenticatedTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembershipsRoute =
  AuthenticatedMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDietRoute = AuthenticatedDietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diet': typeof AuthenticatedDietRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/memberships': typeof AuthenticatedMembershipsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/trainers': typeof AuthenticatedTrainersRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diet': typeof AuthenticatedDietRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/memberships': typeof AuthenticatedMembershipsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/trainers': typeof AuthenticatedTrainersRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diet': typeof AuthenticatedDietRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/memberships': typeof AuthenticatedMembershipsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/trainers': typeof AuthenticatedTrainersRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/branches'
    | '/dashboard'
    | '/diet'
    | '/equipment'
    | '/expenses'
    | '/followups'
    | '/leads'
    | '/members'
    | '/memberships'
    | '/notifications'
    | '/payments'
    | '/plans'
    | '/products'
    | '/reports'
    | '/roles'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/trainers'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attendance'
    | '/branches'
    | '/dashboard'
    | '/diet'
    | '/equipment'
    | '/expenses'
    | '/followups'
    | '/leads'
    | '/members'
    | '/memberships'
    | '/notifications'
    | '/payments'
    | '/plans'
    | '/products'
    | '/reports'
    | '/roles'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/trainers'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attendance'
    | '/_authenticated/branches'
    | '/_authenticated/dashboard'
    | '/_authenticated/diet'
    | '/_authenticated/equipment'
    | '/_authenticated/expenses'
    | '/_authenticated/followups'
    | '/_authenticated/leads'
    | '/_authenticated/members'
    | '/_authenticated/memberships'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/plans'
    | '/_authenticated/products'
    | '/_authenticated/reports'
    | '/_authenticated/roles'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/trainers'
    | '/_authenticated/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trainers': {
      id: '/_authenticated/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof AuthenticatedTrainersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memberships': {
      id: '/_authenticated/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof AuthenticatedMembershipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diet': {
      id: '/_authenticated/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof AuthenticatedDietRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDietRoute: typeof AuthenticatedDietRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMembershipsRoute: typeof AuthenticatedMembershipsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedTrainersRoute: typeof AuthenticatedTrainersRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDietRoute: AuthenticatedDietRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMembershipsRoute: AuthenticatedMembershipsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedTrainersRoute: AuthenticatedTrainersRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
